---
- hosts: all
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image melkeor/simple-devops-image

  - name: push image on to dockerhub
    command: docker push melkeor/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:latest melkeor/simple-devops-image
    ignore_errors: yes